# Generated by Django 3.2 on 2023-05-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restasite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='type',
            field=models.CharField(choices=[('VEG', 'Веганские'), ('BEF', 'Говяжьи'), ('CHI', 'Куриные')], default='NEW', max_length=3, verbose_name='Тип'),
        ),
    ]
