# Generated by Django 3.2 on 2023-05-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restasite', '0003_alter_menu_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='type',
            field=models.CharField(choices=[('VEG', 'Веганские'), ('VEG', 'Салаты'), ('BEF', 'Говяжьи'), ('CHI', 'Куриные')], default='NEW', max_length=4, verbose_name='Тип'),
        ),
    ]
