# Generated by Django 3.2 on 2023-05-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restasite', '0002_alter_menu_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='type',
            field=models.CharField(choices=[('BEF', 'Говяжьи'), ('VEG', 'Веганские'), ('CHI', 'Куриные')], default='NEW', max_length=3, verbose_name='Тип'),
        ),
    ]
