# Generated by Django 3.2 on 2023-05-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restasite', '0004_alter_menu_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='type',
            field=models.CharField(choices=[('CHI', 'Куриные'), ('VEG', 'Салаты'), ('BEF', 'Говяжьи'), ('VEG', 'Веганские')], default='NEW', max_length=4, verbose_name='Тип'),
        ),
    ]
